name: Chimera
channels:
  - pytorch
  - fastai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - cached-property=1.5.2
  - catalogue=2.0.10
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - confection=0.1.4
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cuda-cccl=12.3.101
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.3.101
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - cymem=2.0.6
  - cython-blis=0.7.11
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.5.0
  - fastai=2.7.14
  - fastcore=1.5.29
  - fastdownload=0.0.7
  - fastprogress=1.0.3
  - filelock=3.13.1
  - fonttools=4.25.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - giflib=5.2.1
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.20.0
  - isoduration=20.11.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonpointer=2.1
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.9.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.12
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - langcodes=3.3.0
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.4.107
  - libcurand-dev=10.3.4.107
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - munkres=1.1.4
  - murmurhash=1.0.7
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.4.0
  - openssl=3.0.13
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.1.4
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pillow=10.0.1
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - preshed=3.0.6
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.1
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytorch=2.2.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.3.5
  - rpds-py=0.10.6
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - send2trash=1.8.2
  - setuptools=68.2.2
  - shellingham=1.5.0
  - sip=6.7.12
  - six=1.16.0
  - smart_open=5.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.41.2
  - srsly=2.4.8
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - terminado=0.17.1
  - thinc=8.2.2
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.7.1
  - typer=0.9.0
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - uri-template=1.3.0
  - urllib3=1.26.18
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wasabi=0.9.1
  - wcwidth=0.2.5
  - weasel=0.3.4
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - comm==0.2.1
      - fsspec==2024.2.0
      - gputil==1.4.0
      - ipywidgets==8.1.2
      - jupyterlab-widgets==3.0.10
      - kaggle==1.6.11
      - levenshtein==0.25.0
      - nvidia-ml-py3==7.352.0
      - opendatasets==0.1.22
      - python-slugify==8.0.4
      - rapidfuzz==3.6.1
      - text-unidecode==1.3
      - torch-lr-finder==0.2.1
      - torchaudio==2.2.0
      - torchvision==0.17.0
      - widgetsnbextension==4.0.10
